// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-KotHjjw-5VdMR4Ih-OcKT5VPmTHZ-0',
    appId: '1:1055204675285:android:5957777e60b25b840e5c5c',
    messagingSenderId: '1055204675285',
    projectId: 'dlukitas-2337a',
    storageBucket: 'dlukitas-2337a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7iHt0G2W5OORxKXVWayhnjS3iq74wIn4',
    appId: '1:1055204675285:ios:3457947487e55d730e5c5c',
    messagingSenderId: '1055204675285',
    projectId: 'dlukitas-2337a',
    storageBucket: 'dlukitas-2337a.appspot.com',
    iosClientId:
        '1055204675285-hotlkdrr9tck49grbv2mtg9irs394hm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.dlukitas',
  );
}
